export interface Food {
  id: string
  name: string
  category: string
  subcategory?: string // Para refeições específicas (cafe_manha, almoco, etc)
  calories: number // per 100g
  protein: number // per 100g
  carbs: number // per 100g
  fat: number // per 100g
  fiber: number // per 100g
  unit: string // g, ml, unidade
  commonServing: number // tamanho da porção comum
  mealTime?: string[] // Em quais refeições é comum (cafe_manha, almoco, jantar, lanche)
}

export const foodDatabase: Food[] = [
  // === CAFÉ DA MANHÃ ===
  // Pães e Cereais
  {
    id: "pao_frances",
    name: "Pão francês",
    category: "carboidrato",
    subcategory: "pao",
    calories: 265,
    protein: 8.5,
    carbs: 49,
    fat: 3.2,
    fiber: 2.8,
    unit: "unidade",
    commonServing: 1,
    mealTime: ["cafe_manha"],
  },
  {
    id: "pao_integral",
    name: "Pão integral",
    category: "carboidrato",
    subcategory: "pao",
    calories: 247,
    protein: 13,
    carbs: 41,
    fat: 4.2,
    fiber: 7,
    unit: "fatia",
    commonServing: 2,
    mealTime: ["cafe_manha"],
  },
  {
    id: "aveia",
    name: "Aveia",
    category: "carboidrato",
    subcategory: "cereal",
    calories: 389,
    protein: 17,
    carbs: 66,
    fat: 7,
    fiber: 10,
    unit: "g",
    commonServing: 40,
    mealTime: ["cafe_manha"],
  },
  {
    id: "cuscuz",
    name: "Cuscuz de milho",
    category: "carboidrato",
    subcategory: "cereal",
    calories: 112,
    protein: 3.5,
    carbs: 23,
    fat: 0.5,
    fiber: 2.5,
    unit: "g",
    commonServing: 100,
    mealTime: ["cafe_manha"],
  },
  {
    id: "tapioca",
    name: "Tapioca",
    category: "carboidrato",
    subcategory: "cereal",
    calories: 336,
    protein: 0.2,
    carbs: 87,
    fat: 0.1,
    fiber: 0.9,
    unit: "g",
    commonServing: 50,
    mealTime: ["cafe_manha"],
  },
  {
    id: "granola",
    name: "Granola",
    category: "carboidrato",
    subcategory: "cereal",
    calories: 471,
    protein: 10,
    carbs: 64,
    fat: 20,
    fiber: 8,
    unit: "g",
    commonServing: 30,
    mealTime: ["cafe_manha"],
  },

  // Laticínios para café da manhã
  {
    id: "iogurte_grego",
    name: "Iogurte grego",
    category: "laticinios",
    subcategory: "iogurte",
    calories: 59,
    protein: 10,
    carbs: 3.6,
    fat: 0.4,
    fiber: 0,
    unit: "g",
    commonServing: 170,
    mealTime: ["cafe_manha"],
  },
  {
    id: "iogurte_natural",
    name: "Iogurte natural",
    category: "laticinios",
    subcategory: "iogurte",
    calories: 61,
    protein: 3.5,
    carbs: 4.7,
    fat: 3.3,
    fiber: 0,
    unit: "g",
    commonServing: 170,
    mealTime: ["cafe_manha"],
  },
  {
    id: "queijo_branco",
    name: "Queijo branco",
    category: "laticinios",
    subcategory: "queijo",
    calories: 98,
    protein: 11,
    carbs: 3.4,
    fat: 4.3,
    fiber: 0,
    unit: "g",
    commonServing: 100,
    mealTime: ["cafe_manha"],
  },
  {
    id: "queijo_minas",
    name: "Queijo minas",
    category: "laticinios",
    subcategory: "queijo",
    calories: 253,
    protein: 21,
    carbs: 2.2,
    fat: 18,
    fiber: 0,
    unit: "g",
    commonServing: 50,
    mealTime: ["cafe_manha"],
  },
  {
    id: "leite_desnatado",
    name: "Leite desnatado",
    category: "laticinios",
    subcategory: "leite",
    calories: 34,
    protein: 3.4,
    carbs: 5,
    fat: 0.1,
    fiber: 0,
    unit: "ml",
    commonServing: 200,
    mealTime: ["cafe_manha"],
  },
  {
    id: "leite_integral",
    name: "Leite integral",
    category: "laticinios",
    subcategory: "leite",
    calories: 61,
    protein: 3.2,
    carbs: 4.8,
    fat: 3.3,
    fiber: 0,
    unit: "ml",
    commonServing: 200,
    mealTime: ["cafe_manha"],
  },

  // Frutas para café da manhã
  {
    id: "banana",
    name: "Banana",
    category: "fruta",
    subcategory: "fruta",
    calories: 89,
    protein: 1.1,
    carbs: 23,
    fat: 0.3,
    fiber: 2.6,
    unit: "unidade",
    commonServing: 1,
    mealTime: ["cafe_manha", "lanche"],
  },
  {
    id: "maca",
    name: "Maçã",
    category: "fruta",
    subcategory: "fruta",
    calories: 52,
    protein: 0.3,
    carbs: 14,
    fat: 0.2,
    fiber: 2.4,
    unit: "unidade",
    commonServing: 1,
    mealTime: ["cafe_manha", "lanche"],
  },
  {
    id: "laranja",
    name: "Laranja",
    category: "fruta",
    subcategory: "fruta",
    calories: 47,
    protein: 0.9,
    carbs: 12,
    fat: 0.1,
    fiber: 2.4,
    unit: "unidade",
    commonServing: 1,
    mealTime: ["cafe_manha", "lanche"],
  },
  {
    id: "mamao",
    name: "Mamão",
    category: "fruta",
    subcategory: "fruta",
    calories: 43,
    protein: 0.5,
    carbs: 11,
    fat: 0.3,
    fiber: 1.7,
    unit: "g",
    commonServing: 150,
    mealTime: ["cafe_manha", "lanche"],
  },

  // === ALMOÇO E JANTAR ===
  // Proteínas principais
  {
    id: "frango_peito",
    name: "Peito de frango",
    category: "proteina",
    subcategory: "carne",
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    fiber: 0,
    unit: "g",
    commonServing: 120,
    mealTime: ["almoco", "jantar"],
  },
  {
    id: "frango_coxa",
    name: "Coxa de frango",
    category: "proteina",
    subcategory: "carne",
    calories: 209,
    protein: 26,
    carbs: 0,
    fat: 12,
    fiber: 0,
    unit: "g",
    commonServing: 120,
    mealTime: ["almoco", "jantar"],
  },
  {
    id: "carne_bovina",
    name: "Carne bovina",
    category: "proteina",
    subcategory: "carne",
    calories: 250,
    protein: 26,
    carbs: 0,
    fat: 15,
    fiber: 0,
    unit: "g",
    commonServing: 100,
    mealTime: ["almoco", "jantar"],
  },
  {
    id: "peixe_tilapia",
    name: "Tilápia",
    category: "proteina",
    subcategory: "peixe",
    calories: 96,
    protein: 20,
    carbs: 0,
    fat: 2.3,
    fiber: 0,
    unit: "g",
    commonServing: 100,
    mealTime: ["almoco", "jantar"],
  },
  {
    id: "peixe_sardinha",
    name: "Sardinha",
    category: "proteina",
    subcategory: "peixe",
    calories: 208,
    protein: 24,
    carbs: 0,
    fat: 12,
    fiber: 0,
    unit: "g",
    commonServing: 100,
    mealTime: ["almoco", "jantar"],
  },
  {
    id: "ovo",
    name: "Ovo",
    category: "proteina",
    subcategory: "ovo",
    calories: 155,
    protein: 13,
    carbs: 1.1,
    fat: 11,
    fiber: 0,
    unit: "unidade",
    commonServing: 2,
    mealTime: ["cafe_manha", "almoco", "jantar"],
  },

  // Carboidratos para almoço/jantar
  {
    id: "arroz_branco",
    name: "Arroz branco",
    category: "carboidrato",
    subcategory: "arroz",
    calories: 130,
    protein: 2.7,
    carbs: 28,
    fat: 0.3,
    fiber: 0.4,
    unit: "g",
    commonServing: 150,
    mealTime: ["almoco", "jantar"],
  },
  {
    id: "arroz_integral",
    name: "Arroz integral",
    category: "carboidrato",
    subcategory: "arroz",
    calories: 123,
    protein: 2.6,
    carbs: 23,
    fat: 0.9,
    fiber: 1.8,
    unit: "g",
    commonServing: 150,
    mealTime: ["almoco", "jantar"],
  },
  {
    id: "feijao_carioca",
    name: "Feijão carioca",
    category: "carboidrato",
    subcategory: "leguminosa",
    calories: 77,
    protein: 4.8,
    carbs: 14,
    fat: 0.5,
    fiber: 5.4,
    unit: "g",
    commonServing: 100,
    mealTime: ["almoco", "jantar"],
  },
  {
    id: "feijao_preto",
    name: "Feijão preto",
    category: "carboidrato",
    subcategory: "leguminosa",
    calories: 77,
    protein: 4.8,
    carbs: 14,
    fat: 0.5,
    fiber: 5.4,
    unit: "g",
    commonServing: 100,
    mealTime: ["almoco", "jantar"],
  },
  {
    id: "lentilha",
    name: "Lentilha",
    category: "carboidrato",
    subcategory: "leguminosa",
    calories: 116,
    protein: 9,
    carbs: 20,
    fat: 0.4,
    fiber: 7.9,
    unit: "g",
    commonServing: 100,
    mealTime: ["almoco", "jantar"],
  },
  {
    id: "batata",
    name: "Batata",
    category: "carboidrato",
    subcategory: "tuberculo",
    calories: 77,
    protein: 2,
    carbs: 17,
    fat: 0.1,
    fiber: 2.2,
    unit: "g",
    commonServing: 150,
    mealTime: ["almoco", "jantar"],
  },
  {
    id: "batata_doce",
    name: "Batata doce",
    category: "carboidrato",
    subcategory: "tuberculo",
    calories: 86,
    protein: 1.6,
    carbs: 20,
    fat: 0.1,
    fiber: 3,
    unit: "g",
    commonServing: 200,
    mealTime: ["almoco", "jantar"],
  },
  {
    id: "mandioca",
    name: "Mandioca",
    category: "carboidrato",
    subcategory: "tuberculo",
    calories: 160,
    protein: 1.4,
    carbs: 38,
    fat: 0.3,
    fiber: 1.8,
    unit: "g",
    commonServing: 150,
    mealTime: ["almoco", "jantar"],
  },
  {
    id: "macarrao",
    name: "Macarrão",
    category: "carboidrato",
    subcategory: "massa",
    calories: 131,
    protein: 5,
    carbs: 25,
    fat: 1.1,
    fiber: 1.8,
    unit: "g",
    commonServing: 100,
    mealTime: ["almoco", "jantar"],
  },

  // Vegetais
  {
    id: "alface",
    name: "Alface",
    category: "vegetal",
    subcategory: "folha",
    calories: 15,
    protein: 1.4,
    carbs: 2.9,
    fat: 0.2,
    fiber: 1.3,
    unit: "g",
    commonServing: 80,
    mealTime: ["almoco", "jantar"],
  },
  {
    id: "tomate",
    name: "Tomate",
    category: "vegetal",
    subcategory: "fruto",
    calories: 18,
    protein: 0.9,
    carbs: 3.9,
    fat: 0.2,
    fiber: 1.2,
    unit: "g",
    commonServing: 150,
    mealTime: ["almoco", "jantar"],
  },
  {
    id: "cenoura",
    name: "Cenoura",
    category: "vegetal",
    subcategory: "raiz",
    calories: 41,
    protein: 0.9,
    carbs: 10,
    fat: 0.2,
    fiber: 2.8,
    unit: "g",
    commonServing: 100,
    mealTime: ["almoco", "jantar"],
  },
  {
    id: "brocolis",
    name: "Brócolis",
    category: "vegetal",
    subcategory: "crucifera",
    calories: 34,
    protein: 2.8,
    carbs: 7,
    fat: 0.4,
    fiber: 2.6,
    unit: "g",
    commonServing: 150,
    mealTime: ["almoco", "jantar"],
  },
  {
    id: "couve_flor",
    name: "Couve-flor",
    category: "vegetal",
    subcategory: "crucifera",
    calories: 25,
    protein: 1.9,
    carbs: 5,
    fat: 0.3,
    fiber: 2,
    unit: "g",
    commonServing: 150,
    mealTime: ["almoco", "jantar"],
  },
  {
    id: "abobora",
    name: "Abóbora",
    category: "vegetal",
    subcategory: "cucurbita",
    calories: 26,
    protein: 1,
    carbs: 6.5,
    fat: 0.1,
    fiber: 0.5,
    unit: "g",
    commonServing: 150,
    mealTime: ["almoco", "jantar"],
  },
  {
    id: "chuchu",
    name: "Chuchu",
    category: "vegetal",
    subcategory: "cucurbita",
    calories: 19,
    protein: 0.8,
    carbs: 4.5,
    fat: 0.1,
    fiber: 1.7,
    unit: "g",
    commonServing: 150,
    mealTime: ["almoco", "jantar"],
  },
  {
    id: "berinjela",
    name: "Berinjela",
    category: "vegetal",
    subcategory: "solanacea",
    calories: 25,
    protein: 1,
    carbs: 6,
    fat: 0.2,
    fiber: 3,
    unit: "g",
    commonServing: 150,
    mealTime: ["almoco", "jantar"],
  },
  {
    id: "abobrinha",
    name: "Abobrinha",
    category: "vegetal",
    subcategory: "cucurbita",
    calories: 17,
    protein: 1.2,
    carbs: 3.1,
    fat: 0.3,
    fiber: 1,
    unit: "g",
    commonServing: 150,
    mealTime: ["almoco", "jantar"],
  },

  // Gorduras
  {
    id: "azeite_oliva",
    name: "Azeite de oliva",
    category: "gordura",
    subcategory: "oleo",
    calories: 884,
    protein: 0,
    carbs: 0,
    fat: 100,
    fiber: 0,
    unit: "ml",
    commonServing: 10,
    mealTime: ["almoco", "jantar"],
  },
  {
    id: "oleo_soja",
    name: "Óleo de soja",
    category: "gordura",
    subcategory: "oleo",
    calories: 884,
    protein: 0,
    carbs: 0,
    fat: 100,
    fiber: 0,
    unit: "ml",
    commonServing: 10,
    mealTime: ["almoco", "jantar"],
  },

  // === LANCHE ===
  // Frutas para lanche
  {
    id: "pera",
    name: "Pera",
    category: "fruta",
    subcategory: "fruta",
    calories: 57,
    protein: 0.4,
    carbs: 15,
    fat: 0.1,
    fiber: 3.1,
    unit: "unidade",
    commonServing: 1,
    mealTime: ["lanche"],
  },
  {
    id: "uva",
    name: "Uva",
    category: "fruta",
    subcategory: "fruta",
    calories: 62,
    protein: 0.6,
    carbs: 16,
    fat: 0.2,
    fiber: 0.9,
    unit: "g",
    commonServing: 100,
    mealTime: ["lanche"],
  },
  {
    id: "manga",
    name: "Manga",
    category: "fruta",
    subcategory: "fruta",
    calories: 60,
    protein: 0.8,
    carbs: 15,
    fat: 0.4,
    fiber: 1.6,
    unit: "g",
    commonServing: 150,
    mealTime: ["lanche"],
  },
  {
    id: "abacaxi",
    name: "Abacaxi",
    category: "fruta",
    subcategory: "fruta",
    calories: 50,
    protein: 0.5,
    carbs: 13,
    fat: 0.1,
    fiber: 1.4,
    unit: "g",
    commonServing: 150,
    mealTime: ["lanche"],
  },

  // Oleaginosas para lanche
  {
    id: "amendoas",
    name: "Amêndoas",
    category: "gordura",
    subcategory: "oleaginosa",
    calories: 579,
    protein: 21,
    carbs: 22,
    fat: 50,
    fiber: 12,
    unit: "g",
    commonServing: 30,
    mealTime: ["lanche"],
  },
  {
    id: "castanha_caju",
    name: "Castanha de caju",
    category: "gordura",
    subcategory: "oleaginosa",
    calories: 553,
    protein: 18,
    carbs: 30,
    fat: 44,
    fiber: 3.3,
    unit: "g",
    commonServing: 30,
    mealTime: ["lanche"],
  },
  {
    id: "castanha_para",
    name: "Castanha do Pará",
    category: "gordura",
    subcategory: "oleaginosa",
    calories: 656,
    protein: 14,
    carbs: 12,
    fat: 66,
    fiber: 7.5,
    unit: "g",
    commonServing: 30,
    mealTime: ["lanche"],
  },
  {
    id: "pasta_amendoim",
    name: "Pasta de amendoim",
    category: "gordura",
    subcategory: "pasta",
    calories: 588,
    protein: 25,
    carbs: 20,
    fat: 50,
    fiber: 8,
    unit: "g",
    commonServing: 20,
    mealTime: ["lanche"],
  },
]

export function getFoodById(id: string): Food | undefined {
  return foodDatabase.find((food) => food.id === id)
}

export function getFoodsByCategory(category: string): Food[] {
  return foodDatabase.filter((food) => food.category === category)
}

export function getFoodsByMealTime(mealTime: string): Food[] {
  return foodDatabase.filter((food) => food.mealTime?.includes(mealTime))
}

export function getFoodsBySubcategory(subcategory: string): Food[] {
  return foodDatabase.filter((food) => food.subcategory === subcategory)
}

export function calculateNutrition(
  foodId: string,
  amount: number,
): {
  calories: number
  protein: number
  carbs: number
  fat: number
  fiber: number
} {
  const food = getFoodById(foodId)
  if (!food) return { calories: 0, protein: 0, carbs: 0, fat: 0, fiber: 0 }

  const multiplier = food.unit === "unidade" ? amount : amount / 100

  return {
    calories: Math.round(food.calories * multiplier),
    protein: Math.round(food.protein * multiplier * 10) / 10,
    carbs: Math.round(food.carbs * multiplier * 10) / 10,
    fat: Math.round(food.fat * multiplier * 10) / 10,
    fiber: Math.round(food.fiber * multiplier * 10) / 10,
  }
}
